name: Ping Render App

on:
  schedule:
    - cron: "*/5 * * * *"   # Mỗi 5 phút (UTC)
  workflow_dispatch:        # Cho phép chạy thủ công nếu cần

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl to keep app alive
        run: curl -s https://soometa-be.onrender.com > /dev/null
